stages:
  - test

unit-test:
  stage: test
  image: dh-iutl.univ-artois.fr/composer
  tags:
    - docker
  script:
    - composer install --no-interaction --prefer-dist --optimize-autoloader
    - echo "Running PHPUnit tests..."
    - php artisan test
  only:
    - main
    - dev
