stages:
  - test

unit-test:
  stage: test
  image: dh-iutl.univ-artois.fr/php
  tags:
    - docker
  script:
    - echo "Running PHPUnit tests..."
    - php artisan test
  only:
    - main
    - dev
