stages:
  - build
  - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE/php-app:latest

build-image:
  stage: build
  tags:
    - docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -f Dockerfile -t $IMAGE_TAG .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker push $IMAGE_TAG

unit-test:
  stage: test
  tags:
    - docker
  image: $IMAGE_TAG
  script:
    - ./vendor/bin/phpunit
  only:
    - main
    - dev
