@startuml
hide empty members

class USER {
    user_id SERIAL <<PK>>
    user_name VARCHAR
    user_email VARCHAR
    user_password VARCHAR
}

class CUSTOMER {
    cust_id SERIAL <<PK>>
    cust_first_name VARCHAR
    cust_last_name VARCHAR
    cust_birthday DATE
    cust_email VARCHAR
    cust_phone VARCHAR
    cust_num VARCHAR
    cust_street VARCHAR
    cust_zip VARCHAR
    cust_city VARCHAR
    cust_country VARCHAR
    cust_num_bill VARCHAR
    cust_street_bill VARCHAR
    cust_zip_bill VARCHAR
    cust_city_bill VARCHAR
    cust_country_bill VARCHAR
    user_id INT <<FK>>
}

class RENTAL {
    rental_id SERIAL <<PK>>
    rental_start DATETIME
    rental_end DATETIME
    rental_nb_days INT
    rental_total_price FLOAT
    cust_id INT <<FK>>
    waranty_id INT <<FK>>
}

class LICENSE {
    license_num VARCHAR <<PK>>
    license_acquirement_date DATE
    license_distribution_date VARCHAR
    license_country VARCHAR
    cust_id INT <<FK>>
}

class WARANTY {
    waranty_id SERIAL <<PK>>
    waranty_name VARCHAR
    waranty_price FLOAT
}

class AMENDMENT {
    amendment_id SERIAL <<PK>>
    amendment_name VARCHAR
    amendment_content VARCHAR
}

class DOCUMENT {
    doc_id SERIAL <<PK>>
    doc_type ENUM
    doc_url VARCHAR
    rental_id INT <<FK>>
}

class WITHDRAWAL {
    withdrawal_id SERIAL <<PK>>
    withdrawal_datetime DATE
    user_id INT <<FK>>
    rental_id INT <<FK>>
}

class HANDOVER {
    handover_id SERIAL <<PK>>
    handover_datetime DATE
    user_id INT <<FK>>
    rental_id INT <<FK>>
}

class CAR {
    car_plate VARCHAR <<PK>>
    car_type ENUM
    car_condition VARCHAR
    car_remaining_gas FLOAT
    car_price_day FLOAT
    category_id INT <<FK>>
    agency_id INT <<FK>>
}

class OPTION {
    option_id SERIAL <<PK>>
    option_name VARCHAR
    option_desc VARCHAR
    option_price FLOAT
}

class CATEGORY {
    category_id SERIAL <<PK>>
    category_name VARCHAR
    category_description VARCHAR
}

class AGENCY {
    agency_id SERIAL <<PK>>
    agency_num VARCHAR
    agency_street VARCHAR
    agency_zip VARCHAR
    agency_city VARCHAR
    agency_country VARCHAR
}

CAR "*" -- "1" AGENCY
CAR "*" -- "1" CATEGORY
CAR "1" -- "*" RENTAL
RENTAL "1" -- "*" AMENDMENT
RENTAL "1" -- "0..1" WITHDRAWAL
WITHDRAWAL "*" -- "1" USER
USER "0..1" -- "0..1" CUSTOMER
LICENSE "0..1" -- "1" CUSTOMER
WARANTY "0..1" -- "*" RENTAL
OPTION "*" -- "*" RENTAL
DOCUMENT "0..*" -- "1" RENTAL
USER "1" -- "*" HANDOVER
RENTAL "1" -- "0..1" HANDOVER
CUSTOMER "1" -- "*" RENTAL

@enduml
